#!/usr/bin/env zsh

# Stop zsh themes from complaining
export TERM="xterm-256color"

# Why not the default, though?
export EDITOR=/usr/bin/vim

# Tells 'less' not to paginate if less than a page
export LESS="-eirMXF"

# Hook for desk activation ####################################################
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true

# Source all files in the env-files.d directory ###############################
if [[ -d ${HOME}/.env-files.d ]]; then
  for f in ${HOME}/.env-files.d/*; do
      source "${f}"
  done
fi
###############################################################################

# Configure history ###########################################################
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
###############################################################################

# Configure zsh-autocomplete###################################################
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
###############################################################################

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export MAVEN_HOME=/opt/apache-maven-3.9.6
